# Generated by Django 5.1.2 on 2024-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
