# Generated by Django 5.1.1 on 2024-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_user_alter_appointment_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_type',
            field=models.CharField(choices=[('Grooming', 'grooming'), ('Boarding', 'boarding')], default='grooming', max_length=20),
        ),
    ]
