# Generated by Django 5.1.1 on 2024-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_type',
            field=models.CharField(choices=[('Grooming', 'Grooming'), ('Boarding', 'Boarding')], default='Grooming', max_length=20),
        ),
    ]
